#!/bin/bash

# 快速为用户添加积分的脚本
# 使用方法：./quick-add-credits.sh <用户邮箱> <积分数量> [备注]
# 示例：./quick-add-credits.sh user@example.com 100 "手动充值"

# 检查参数
if [ $# -lt 2 ]; then
    echo "使用方法：./quick-add-credits.sh <用户邮箱> <积分数量> [备注]"
    echo "示例：./quick-add-credits.sh user@example.com 100 '手动充值'"
    exit 1
fi

USER_EMAIL="$1"
CREDITS="$2"
NOTE="${3:-手动添加积分}"
TIMESTAMP=$(date +%s)

# 验证积分数量是否为正整数
if ! [[ "$CREDITS" =~ ^[1-9][0-9]*$ ]]; then
    echo "错误：积分数量必须是正整数"
    exit 1
fi

echo "==========================================="
echo "为用户添加积分 - SQL 语句生成器"
echo "==========================================="
echo "用户邮箱: $USER_EMAIL"
echo "积分数量: $CREDITS"
echo "备注信息: $NOTE"
echo "==========================================="
echo ""
echo "请按以下步骤操作："
echo "1. 登录 Cloudflare Dashboard"
echo "2. 进入 D1 数据库管理页面"
echo "3. 复制并执行以下 SQL 语句："
echo ""
echo "-- ========================================"
echo "-- 步骤 1: 查找用户ID"
echo "-- ========================================"
echo "SELECT id, email, nickname FROM users WHERE email = '$USER_EMAIL';"
echo ""
echo "-- ========================================"
echo "-- 步骤 2: 添加积分记录（请将 USER_ID 替换为上面查询到的实际用户ID）"
echo "-- ========================================"
echo "INSERT INTO credit_records ("
echo "  user_id,"
echo "  credits,"
echo "  remaining_credits,"
echo "  trans_type,"
echo "  source_type,"
echo "  source_id,"
echo "  note,"
echo "  created_at,"
echo "  updated_at"
echo ") VALUES ("
echo "  USER_ID,  -- 请替换为步骤1查询到的实际用户ID"
echo "  $CREDITS,"
echo "  $CREDITS,"
echo "  'adjustment',"
echo "  'manual',"
echo "  'admin_manual_$TIMESTAMP',"
echo "  '$NOTE',"
echo "  strftime('%s', 'now'),"
echo "  strftime('%s', 'now')"
echo ");"
echo ""
echo "-- ========================================"
echo "-- 步骤 3: 验证添加结果"
echo "-- ========================================"
echo "SELECT "
echo "  cr.id,"
echo "  u.email,"
echo "  u.nickname,"
echo "  cr.credits,"
echo "  cr.remaining_credits,"
echo "  cr.trans_type,"
echo "  cr.note,"
echo "  datetime(cr.created_at, 'unixepoch') as created_time"
echo "FROM credit_records cr"
echo "JOIN users u ON cr.user_id = u.id"
echo "WHERE u.email = '$USER_EMAIL'"
echo "ORDER BY cr.created_at DESC"
echo "LIMIT 5;"
echo ""
echo "-- ========================================"
echo "-- 步骤 4: 查看用户总积分"
echo "-- ========================================"
echo "SELECT "
echo "  u.email,"
echo "  u.nickname,"
echo "  SUM(cr.remaining_credits) as total_available_credits"
echo "FROM users u"
echo "LEFT JOIN credit_records cr ON u.id = cr.user_id"
echo "WHERE u.email = '$USER_EMAIL'"
echo "GROUP BY u.id, u.email, u.nickname;"
echo ""
echo "✅ SQL 语句生成完成！"
echo "请复制上面的 SQL 语句到 Cloudflare D1 控制台执行"
echo "==========================================="
